# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fc0283cf70026b56c14c02cb0bc7f5ef9a178b33cf5f1e57f6a7da0abbe68fa3ae693751d78afe4dcd5c4d9d3fd5a17efb2db000a47b2ba56653b9f4b7671fe

test:
  secret_key_base: 2ecc27e8183821cdbfebcbbd18f1f2ce4851dcba82fe80b77ae97a3ee9fe9a150ee8d1cebb1103beb0b81a864c90784d0ec2b677e068d3c06b87bea5a7a4884d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
